export const products = [
    {
        id: 1,
        name: "Fantastic Foods",
        category: "Grocery",
        location: "Thane",
        timing: "8:00AM to 7:00PM " ,
    },
    {
        id: 2,
        name: "Cake House",
        category: "Baker",
        location: "Nashik",
        timing: "8:00AM to 8:00PM",
    },
    {
        id: 3,
        name: "Meat Mind",
        category: "Butcher",
        location: "Thane",
        timing: "9:00AM to 5:00PM",
    },
    {
        id: 4,
        name: "Smart Pharmacy",
        category: "Chemist",
        location: "Nashik",
        timing: "7:00AM to 9:00PM",
    },
    {
        id: 5,
        name: "Snack Rack",
        category: "Baker",
        location: "Nagpur",
        timing: "8:00AM to 8:00PM",
    },
    {
        id: 6,
        name: "Meat Corner",
        category: "Butcher",
        location: "Pune",
        timing: "9:00AM to 5:00PM",
    },
    {
        id: 7,
        name: "Sweet Words",
        category: "Stationery",
        location: "Ahmednagar",
        timing: "8:00AM to 7:00PM",
    },
    {
        id: 8,
        name: "Fresh Mart",
        category: "Grocery",
        location: "Pune",
        timing: "7:00AM to 6:00PM",
    },
    {
        id: 9,
        name: "Paper Corner",
        category: "Stationery",
        location: "Solapur",
        timing: "8:00AM to 7:00PM",
    },
    {
        id: 10,
        name: "Medlife",
        category: "Chemist",
        location: "Mumbai Suburban",
        timing: "7:00AM to 9:00PM",
    },
    
]